version: "3"

services:
  web:
    container_name: web
    build: .
    command: /scripts/DEV_server_run.sh
    # command: /scripts/ASGI_server_run.sh
    ports:
      - "8000:8000"
    volumes:
      - django_dev:/app
    env_file:
      - .env
    environment:
      - POSTGRES_NAME=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:13
    pull_policy: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

volumes:
  postgres_data:
    name: postgres_data

  django_dev:
    name: django_dev
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${PWD}/src

networks:
  default:
    name: django_network
